// This file is auto-generated by @hey-api/openapi-ts

import { type Options, uploadFile, addPet, updatePet, findPetsByStatus, findPetsByTags, deletePet, getPetById, updatePetWithForm, getInventory, placeOrder, deleteOrder, getOrderById, createUsersWithListInput, deleteUser, getUserByName, updateUser, loginUser, logoutUser, createUsersWithArrayInput, createUser } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/vue-query';
import type { UploadFileData, UploadFileResponse, AddPetData, UpdatePetData, FindPetsByStatusData, FindPetsByTagsData, DeletePetData, GetPetByIdData, UpdatePetWithFormData, GetInventoryData, PlaceOrderData, PlaceOrderResponse, DeleteOrderData, GetOrderByIdData, CreateUsersWithListInputData, DeleteUserData, GetUserByNameData, UpdateUserData, LoginUserData, LogoutUserData, CreateUsersWithArrayInputData, CreateUserData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const uploadFileQueryKey = (options: Options<UploadFileData>) => createQueryKey('uploadFile', options);

/**
 * uploads an image
 */
export const uploadFileOptions = (options: Options<UploadFileData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await uploadFile({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: uploadFileQueryKey(options)
    });
};

/**
 * uploads an image
 */
export const uploadFileMutation = (options?: Partial<Options<UploadFileData>>): UseMutationOptions<UploadFileResponse, DefaultError, Options<UploadFileData>> => {
    const mutationOptions: UseMutationOptions<UploadFileResponse, DefaultError, Options<UploadFileData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await uploadFile({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addPetQueryKey = (options: Options<AddPetData>) => createQueryKey('addPet', options);

/**
 * Add a new pet to the store
 */
export const addPetOptions = (options: Options<AddPetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await addPet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: addPetQueryKey(options)
    });
};

/**
 * Add a new pet to the store
 */
export const addPetMutation = (options?: Partial<Options<AddPetData>>): UseMutationOptions<unknown, DefaultError, Options<AddPetData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddPetData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await addPet({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update an existing pet
 */
export const updatePetMutation = (options?: Partial<Options<UpdatePetData>>): UseMutationOptions<unknown, DefaultError, Options<UpdatePetData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdatePetData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updatePet({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const findPetsByStatusQueryKey = (options: Options<FindPetsByStatusData>) => createQueryKey('findPetsByStatus', options);

/**
 * Finds Pets by status
 * Multiple status values can be provided with comma separated strings
 */
export const findPetsByStatusOptions = (options: Options<FindPetsByStatusData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await findPetsByStatus({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: findPetsByStatusQueryKey(options)
    });
};

export const findPetsByTagsQueryKey = (options: Options<FindPetsByTagsData>) => createQueryKey('findPetsByTags', options);

/**
 * Finds Pets by tags
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @deprecated
 */
export const findPetsByTagsOptions = (options: Options<FindPetsByTagsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await findPetsByTags({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: findPetsByTagsQueryKey(options)
    });
};

/**
 * Deletes a pet
 */
export const deletePetMutation = (options?: Partial<Options<DeletePetData>>): UseMutationOptions<unknown, DefaultError, Options<DeletePetData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeletePetData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deletePet({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPetByIdQueryKey = (options: Options<GetPetByIdData>) => createQueryKey('getPetById', options);

/**
 * Find pet by ID
 * Returns a single pet
 */
export const getPetByIdOptions = (options: Options<GetPetByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPetById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPetByIdQueryKey(options)
    });
};

export const updatePetWithFormQueryKey = (options: Options<UpdatePetWithFormData>) => createQueryKey('updatePetWithForm', options);

/**
 * Updates a pet in the store with form data
 */
export const updatePetWithFormOptions = (options: Options<UpdatePetWithFormData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await updatePetWithForm({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: updatePetWithFormQueryKey(options)
    });
};

/**
 * Updates a pet in the store with form data
 */
export const updatePetWithFormMutation = (options?: Partial<Options<UpdatePetWithFormData>>): UseMutationOptions<unknown, DefaultError, Options<UpdatePetWithFormData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdatePetWithFormData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updatePetWithForm({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getInventoryQueryKey = (options?: Options<GetInventoryData>) => createQueryKey('getInventory', options);

/**
 * Returns pet inventories by status
 * Returns a map of status codes to quantities
 */
export const getInventoryOptions = (options?: Options<GetInventoryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getInventory({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getInventoryQueryKey(options)
    });
};

export const placeOrderQueryKey = (options: Options<PlaceOrderData>) => createQueryKey('placeOrder', options);

/**
 * Place an order for a pet
 */
export const placeOrderOptions = (options: Options<PlaceOrderData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await placeOrder({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: placeOrderQueryKey(options)
    });
};

/**
 * Place an order for a pet
 */
export const placeOrderMutation = (options?: Partial<Options<PlaceOrderData>>): UseMutationOptions<PlaceOrderResponse, DefaultError, Options<PlaceOrderData>> => {
    const mutationOptions: UseMutationOptions<PlaceOrderResponse, DefaultError, Options<PlaceOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await placeOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete purchase order by ID
 * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
 */
export const deleteOrderMutation = (options?: Partial<Options<DeleteOrderData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteOrderData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteOrderData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteOrder({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getOrderByIdQueryKey = (options: Options<GetOrderByIdData>) => createQueryKey('getOrderById', options);

/**
 * Find purchase order by ID
 * For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
 */
export const getOrderByIdOptions = (options: Options<GetOrderByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getOrderById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getOrderByIdQueryKey(options)
    });
};

export const createUsersWithListInputQueryKey = (options: Options<CreateUsersWithListInputData>) => createQueryKey('createUsersWithListInput', options);

/**
 * Creates list of users with given input array
 */
export const createUsersWithListInputOptions = (options: Options<CreateUsersWithListInputData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createUsersWithListInput({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createUsersWithListInputQueryKey(options)
    });
};

/**
 * Creates list of users with given input array
 */
export const createUsersWithListInputMutation = (options?: Partial<Options<CreateUsersWithListInputData>>): UseMutationOptions<unknown, DefaultError, Options<CreateUsersWithListInputData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CreateUsersWithListInputData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createUsersWithListInput({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete user
 * This can only be done by the logged in user.
 */
export const deleteUserMutation = (options?: Partial<Options<DeleteUserData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await deleteUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByNameQueryKey = (options: Options<GetUserByNameData>) => createQueryKey('getUserByName', options);

/**
 * Get user by user name
 */
export const getUserByNameOptions = (options: Options<GetUserByNameData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUserByName({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserByNameQueryKey(options)
    });
};

/**
 * Updated user
 * This can only be done by the logged in user.
 */
export const updateUserMutation = (options?: Partial<Options<UpdateUserData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginUserQueryKey = (options: Options<LoginUserData>) => createQueryKey('loginUser', options);

/**
 * Logs user into the system
 */
export const loginUserOptions = (options: Options<LoginUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await loginUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: loginUserQueryKey(options)
    });
};

export const logoutUserQueryKey = (options?: Options<LogoutUserData>) => createQueryKey('logoutUser', options);

/**
 * Logs out current logged in user session
 */
export const logoutUserOptions = (options?: Options<LogoutUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await logoutUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: logoutUserQueryKey(options)
    });
};

export const createUsersWithArrayInputQueryKey = (options: Options<CreateUsersWithArrayInputData>) => createQueryKey('createUsersWithArrayInput', options);

/**
 * Creates list of users with given input array
 */
export const createUsersWithArrayInputOptions = (options: Options<CreateUsersWithArrayInputData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createUsersWithArrayInput({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createUsersWithArrayInputQueryKey(options)
    });
};

/**
 * Creates list of users with given input array
 */
export const createUsersWithArrayInputMutation = (options?: Partial<Options<CreateUsersWithArrayInputData>>): UseMutationOptions<unknown, DefaultError, Options<CreateUsersWithArrayInputData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CreateUsersWithArrayInputData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createUsersWithArrayInput({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createUserQueryKey = (options: Options<CreateUserData>) => createQueryKey('createUser', options);

/**
 * Create user
 * This can only be done by the logged in user.
 */
export const createUserOptions = (options: Options<CreateUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createUserQueryKey(options)
    });
};

/**
 * Create user
 * This can only be done by the logged in user.
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<unknown, DefaultError, Options<CreateUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<CreateUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};